### ISSUE TITLE
RequirePackage date parameter fails with empty version string

### ISSUE THREAD

**Issue by ZvikaZ** [raphink/fancytabs#4]
Hi.
I've tried to request the new version, with this line:

```
\RequirePackage{fancytabs}[2016/03/29]
```

But it didn't work.
Tried to go back, to request 1.8, with:

```
\RequirePackage{fancytabs}[2012/09/10]
```

But got the same warning:

```
LaTeX Warning: You have requested, on input line 5, version `2012/09/10' of package fancytabs, but only version `' is available.
```

It's saying that 

```
only version `' is available.
```

It thinks that `fancytab` has an empty string as a version.
Why?

Maybe it's related to this code:

```
\ProvidesPackage{fancytabs}
   [2016/03/29 1.9 Fancy page border tabs with Tikz]

\ProvidesPackage{fancytabs}
```

Maybe the second `ProvidesPackage` without version string overrides the first `ProvidesPackage`?

**Comment by raphink** [comment]
שלומ,

I must say I never use this form, so I haven't noticed the problem. I guess all of my packages have the same bug then.

Does it work if you rebuild without the second line?

**Comment by FrankMittelbach** [comment]
@ZvikaZ With the line

\usepackage{foo}[2012/01/01]

you request that "foo" has *at least* that date so it is a request for a minimal date. You can't get back to an earlier version this way!  Since this year 2018, the package loading interface also supports an extended syntax:

\usepackage{foo}[=2012/01/01]

which attempts to get you the version current at that date. However that only works if the package keeps maintaining older versions. See https://www.latex-project.org/publications/indexbytopic/coding/

Anyhow @raphink the second ProvidesPackage line is wrong and should not be in any package as it overwrite the data from the first (only one set of info is maintained, so after that line version info is no longer known to LaTeX)

**Comment by raphink** [comment]
Ah, thanks for that info @FrankMittelbach. I think I copied that from existing packages and never questioned it.
